FROM eclipse-temurin:17-jdk-jammy AS builder
WORKDIR /app
COPY gradlew settings.gradle build.gradle ./
COPY gradle gradle
RUN chmod +x gradlew && ./gradlew --no-daemon dependencyCache
COPY src src
RUN ./gradlew --no-daemon bootJar
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
ENTRYPOINT ["java","-Xms256m","-Xmx512m","-jar","/app/app.jar"]
