INSERT INTO dealers (id,
                     email,
                     password,
                     name,
                     branch,
                     phone_number,
                     role,
                     master_id,
                     is_deleted,
                     deleted_at,
                     created_at,
                     updated_at)
VALUES (1,
        'dealerA1@example.com',
        '$2b$10$zlKr2tiDpfkNgifvCglcg.c01kXBOJre3Th3v5jqyj2sbPzi66Rfu',
        '딜러A1',
        '미배정',
        '010-1111-2222',
        'DEALER',
        1, -- MasterA(id=1)와 연관
        FALSE,
        NULL,
        NOW(),
        NOW()),
       (2,
        'dealerA2@example.com',
        '$2b$10$zlKr2tiDpfkNgifvCglcg.c01kXBOJre3Th3v5jqyj2sbPzi66Rfu',
        '딜러A2',
        '미배정',
        '010-2222-3333',
        'APPLICANT',
        1, -- MasterA(id=1)와 연관
        FALSE,
        NULL,
        NOW(),
        NOW()),
       (3,
        'dealerB1@example.com',
        '$2b$10$zlKr2tiDpfkNgifvCglcg.c01kXBOJre3Th3v5jqyj2sbPzi66Rfu',
        '딜러B1',
        '미배정',
        '010-3333-4444',
        'APPLICANT',
        2, -- MasterB(id=2)와 연관
        FALSE,
        NULL,
        NOW(),
        NOW()),
       (4,
        'dealerC1@example.com',
        '$2b$10$zlKr2tiDpfkNgifvCglcg.c01kXBOJre3Th3v5jqyj2sbPzi66Rfu',
        '딜러C1',
        '미배정',
        '010-4444-5555',
        'APPLICANT',
        3, -- MasterC(id=3)와 연관
        FALSE,
        NULL,
        NOW(),
        NOW());
