INSERT INTO users (id,
                   email,
                   password,
                   name,
                   date_of_birth,
                   phone_number,
                   address,
                   role,
                   is_deleted,
                   deleted_at,
                   created_at,
                   updated_at)
VALUES (1,
        'user01@example.com',
        '$2b$10$zlKr2tiDpfkNgifvCglcg.c01kXBOJre3Th3v5jqyj2sbPzi66Rfu',
        '사용자01',
        '1990-01-01',
        '010-1111-1111',
        '서울시 강남구 역삼동 1-1',
        'USER',
        FALSE,
        NULL,
        NOW(),
        NOW()),
       (2,
        'user02@example.com',
        '$2b$10$zlKr2tiDpfkNgifvCglcg.c01kXBOJre3Th3v5jqyj2sbPzi66Rfu',
        '사용자02',
        '1990-02-02',
        '010-2222-2222',
        '서울시 강남구 역삼동 2-2',
        'USER',
        FALSE,
        NULL,
        NOW(),
        NOW()),
       (3,
        'user03@example.com',
        '$2b$10$zlKr2tiDpfkNgifvCglcg.c01kXBOJre3Th3v5jqyj2sbPzi66Rfu',
        '사용자03',
        '1990-03-03',
        '010-3333-3333',
        '서울시 강남구 역삼동 3-3',
        'USER',
        FALSE,
        NULL,
        NOW(),
        NOW());
