# .github/workflows/deploy.yml
name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          port:     ${{ secrets.EC2_SSH_PORT }}  # 대부분 기본 22번
          timeout: 1800
          script: |
            set -e
            cd /home/ec2-user/app/osid-back
            git fetch origin main
            git reset --hard origin/main
            docker-compose pull --ignore-pull-failures
            docker-compose up -d --build
